# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml

config.load_autoconfig(True)
config.bind('<Alt-Ctrl-u>', 'spawn --userscript qute-keepassxc --key E8334CE6752602E76548A828ACBDF9416E3C7B5D', mode='insert')
config.bind('pw', 'spawn --userscript qute-keepassxc --key E8334CE6752602E76548A828ACBDF9416E3C7B5D', mode='normal')


c.content.autoplay = False

## In v2.0.0+, use next if you use Adblock Plus AND hosts blocking 
c.content.blocking.method = 'both'

c.content.default_encoding = 'utf-8'

c.content.geolocation = False

## Display PDFs within qutebrowser
c.content.pdfjs = True

config.set("colors.webpage.darkmode.enabled", True)
