#!/bin/sh
# shellcheck disable=SC2155

# Profile file, runs on login. Environmental variables are set here.

# Add all directories in `~/.local/bin` to $PATH
export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

# Default programs:
export EDITOR="nvim"
export VISUAL="nvim"

export TERMINAL="alacritty"
export TERMINAL_PROG="alacritty"
if [ -n "$DISPLAY" ]; then
    export BROWSER=firefox
else 
    export BROWSER=lynx
fi


# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.

export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export TMUX_TMPDIR="$XDG_RUNTIME_DIR"

export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS="R"
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"

export LEDGER_FILE="$HOME/mydir/accounting/all.ledger"

[ -e ~/mydir/notes/.zsh_secret ] && [ ! -e ~/.zsh_secret ] && ln -s ~/mydir/notes/.zsh_secret ~/.zsh_secret
[ -e ~/.zsh_secret ] && . "$HOME/.zsh_secret"



echo "before exec startx $XINITRC"
# Start graphical server on user's current tty if not already running.
# [ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"

# startx when logged in
if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
    exec startx $XINITRC
fi

